### ISSUE TITLE
[BUG] KeyError: 'paid_tax_amount'

### ISSUE THREAD

**Issue by dimitarsm** [doino-gretchenliev/revolut-stocks#11]
**Describe the bug**

[INFO]: Generating [statements.csv] file.
[INFO]: Populating exchange rates.
[INFO]: Calculating dividends information.
[INFO]: Generating [app8-part4-1.csv] file.
Traceback (most recent call last):
File "C:\Downloads\Stocks Calc\revolut-stocks-main\stocks.py", line 97, in <module>
main()
File "C:\Downloads\Stocks Calc\revolut-stocks-main\stocks.py", line 65, in main
export_app8_part4_1(os.path.join(parsed_args.output_dir, "app8-part4-1.csv"), dividends)
File "C:\Downloads\Stocks Calc\revolut-stocks-main\libs\csv.py", line 84, in export_app8_part4_1
dividends = [
File "C:\Downloads\Stocks Calc\revolut-stocks-main\libs\csv.py", line 90, in <listcomp>
"paid_tax_amount": dividend["paid_tax_amount"].quantize(decimal.Decimal(NAP_DIGIT_PRECISION)),
KeyError: 'paid_tax_amount'

**To Reproduce**
Executed command.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS] Windows 10
 - Version: Git commit hash. You can obtain the hash with the following command: `git rev-parse HEAD`.

**Additional context**

**Comment by doino-gretchenliev** [comment]
The bug occurred due to a lack of paid tax at the source for some dividends. Although some Revolut users have reported the same behavior, please compare the generated `statements.csv` file with your statement files. If the statement files were parsed correctly the `statements.csv` file should contain all activities, including every DIV and DIVNRA activity.

For those dividends, for which was not paid tax at the source(missing DIVNRA activity), NAP will request 5% tax. The calculator accounts for that case.

The bug was fixed with this commit: https://github.com/doino-gretchenliev/revolut-stocks/commit/599f784f1db53d001ba1fe80851bbf8b5b03f160

**Comment by dimitarsm** [comment]
Great stuff, thanks for that. I saw which company that is and fixed it :) Weird they have not charged a dividend tax...
