### ISSUE TITLE
feature request: support other denomination currencies

### ISSUE THREAD

**Issue by balazsbanyai** [doino-gretchenliev/revolut-stocks#29]
Hello, 

Thank you very much for this excellent work! I was able to alter the code very easily, to use HUF rates as the denomination currency, so this tool was a huge help! I was wondering if you would be open to accept PRs to extend the functionality for other national banks than the bulgarian, or I should just fork the repo and develop for the hungarian calculations separately?

Thank you very much again, you saved me a ton of time!

**Comment by doino-gretchenliev** [comment]
Hello. The calculator was developed in accordance with Bulgaria taxing law. In other to work for other countries the correctness of its calculations should be verified. That’s is not possible for me at the moment. Because of that if you can commit to verifying and supporting the operation of the calculator for Hungary I'm open to your PRs.

**Comment by balazsbanyai** [comment]
Awesome, thank you very much!
